// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InvoiceFilterInput struct {
	ID          *string  `json:"id"`
	DateCreated *string  `json:"DateCreated"`
	From        *string  `json:"From"`
	Address     *string  `json:"Address"`
	Amount      *float64 `json:"Amount"`
}

type InvoiceInput struct {
	ID          string  `json:"id"`
	DateCreated string  `json:"DateCreated"`
	From        string  `json:"From"`
	Address     string  `json:"Address"`
	Amount      float64 `json:"Amount"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type PaginatedInvoicesReturn struct {
	Data  []*Invoice `json:"data"`
	Total int        `json:"total"`
}

type UpdateUser struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type VerifyToken struct {
	Token string `json:"token"`
}
